# Site settings
baseurl = "https://ileenamitra.github.io" #without ending slash
languageCode = "en-us"
title = "Ileena Mitra"
theme = ""
themesDir = "."

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]


[params]

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Ileena Mitra"
    # Avatars can be written to images/avatars/
    avatar = "ileenamitra.jpg"
    position = "Genomics Scientist"
    livesIn = "Bioinformatics PhD" #
    scope = [
        "Biotech Enthusiast",
        "Avid Runner",
        "Dog Mom"
      ]
    biography = """I do computational medical research in  Dr. Melissa Gymrek's lab.
    My work focuses on understanding how repetitive genetic variation impacts psychiatric diseases.
    When I'm not obsessively on my laptop, I like to play with my doggie, eat chocolate ice cream,
    and enjoy the sun always shining in San Diego, California."""


  # Social settings
  # You may change these with your social links or add others
  [[params.social]]
    title = "GoogleScholar"
    icon = "fa-google"
    link = "https://scholar.google.com/citations?user=amri0HUAAAAJ&hl=en"
    target = "_blank"

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/ileena_mitra"
    target = "_blank"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/ileena-mitra"
    target = "_blank"

  [[params.social]]
    title = "GitHub"
    icon = "fa-github"
    link = "https://github.com/ileenamitra"
    target = "_blank"

  [[params.social]]
    title = "GymrekLab"
    icon = "fa-users"
    link = "http://gymreklab.com/"
    target = "_blank"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Ileena Mitra"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"
